###############################################################################
# Secrets — Credentials for InfluxDB and Grafana
# In production, use SealedSecrets, Vault, or OpenShift secret injection
# These are base64 encoded placeholder values — CHANGE BEFORE DEPLOYING
###############################################################################
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
  namespace: perf-testing
  labels:
    app.kubernetes.io/part-of: jmeter-platform
    app.kubernetes.io/component: influxdb
type: Opaque
data:
  # echo -n 'admin' | base64
  INFLUXDB_ADMIN_USER: YWRtaW4=
  # echo -n 'changeme123' | base64
  INFLUXDB_ADMIN_PASSWORD: Y2hhbmdlbWUxMjM=
  INFLUXDB_DB: am1ldGVy
  INFLUXDB_USER: am1ldGVy
  INFLUXDB_USER_PASSWORD: am1ldGVyMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  namespace: perf-testing
  labels:
    app.kubernetes.io/part-of: jmeter-platform
    app.kubernetes.io/component: grafana
type: Opaque
data:
  # echo -n 'admin' | base64
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  # echo -n 'changeme123' | base64
  GF_SECURITY_ADMIN_PASSWORD: Y2hhbmdlbWUxMjM=
